### ISSUE TITLE
Doesn't work with Windows7-x64

### ISSUE THREAD

**Issue by Deviaphan** [coin3d/sowin#33]
Program stuck in 'SoWin::mainLoop();' function. CoinTest.exe works fine, but all SoWin examples stuck in mainLoop function.
All examples works on Windows10-x64 (even on clean VBox system + redist) but stucked on Win7-x64 (clean VBox system + vsredist). I'm trying coin3d+sowin from source and from release(msvc15-x64)-zip files.
Build examples in MS VisualStudio 2019 (ver 16.6.3) with last Win10 toolset.

**Comment by VolkerEnderlein** [comment]
I haven`t faced any problems in building and running the examples/packages from source and from binaries for all supported platforms. I test the linux and macOS builds on VBox. with no problems at all. But will try again for Windows7-x64. What specific version of VBox are you using? Is other OpenGL based software running successfully? 
"_I'm trying coin3d+sowin from source and from release(msvc15-x64)-zip files.
Build examples in MS VisualStudio 2019 (ver 16.6.3) with last Win10 toolset._"
The releases msvc16-x64 should be usable straight forward with your compiler. You might also give the packages in the CI builds section of the releases a try. They always contain the latest successful build artifacts from the CI.

**Comment by Deviaphan** [comment]
Oracle Virtual Box 6.1.10 r138449 (Qt5.6.2)
But I have this issue on real PC with Win7 Pro, service pack 1, and use VBox to confirm this issue.
with old coin/sowin versions (about two years ago) all works perfect.
VBox running on Ryzen7 3700X, I have some problems with virtualization, so I'm not sure about virtualization correct.
Real PC is old and have old GPU ATI Radeon 4850, last driver from 2013y, maybe this is problem...

coin3d and sowin1 configured for MSVC-16-2019 (x64, native MSVC compiler) with last CMake, all default settings. boost 1.73.0.

With Win10-x64 I can use binary from 'msvc15-x64' (and compiling app in VS2019, works perfect), but with Cl 'sowin1 msvc16-x64.zip' app crashes with this error dlg. Both coin3d and sowin1 from Cl msvc16-64 zip files.

![err](https://user-images.githubusercontent.com/20601357/86308706-22734880-bc44-11ea-9553-942097c132b7.png)

**Comment by Deviaphan** [comment]
Build debug version of standalone.exe. Win SDK 8.1, platform toolset v142
Works perfect in Win10 and stuck in Win7 (compiling with Win7 real PC).

void
SoWin::mainLoop(void)
{
  MSG msg;
  while (TRUE) {
    // FIXME: shouldn't this be a while loop, i.e. process all
    // messages, before doing the idle tasks? 20040721 mortene.
    if (GetQueueStatus(QS_ALLINPUT) != 0) { // if messagequeue != empty
      BOOL bRet;
      if ((bRet = GetMessage(&msg, NULL, 0, 0)) != 0){ // if msg != WM_QUIT
        if (bRet == -1){
          // FIXME: handle the error and possibly exit
          break;
        }
        else {
          TranslateMessage(&msg); 
          DispatchMessage(&msg); 
        }
      }
      else break; // msg == WM_QUIT
    }
    else if (SoWinP::idleSensorId != 0) {
      doIdleTasks();
    }
    else {
      **WaitMessage();  // <<<<<<<<< always this branch**
    }
  }
// Disabled invocation of SoWin::done(), since this calls SoDB::finish(),
// which means we would run into issues doing the usual...
//    SoWin::mainLoop();
//    root->unref();
}

**Comment by VolkerEnderlein** [comment]
Finally found the time to further investigate the issue. I installed a clean virtual Windows 7 x64 machine, the Visual C++ runtime redistributable package and copied the version of Coin4/SoWin1/SampleApplication built with VS2019 x64 to this machine. Build system is Windows - 10.0.18363 - AMD64, Windows 10 1909, VS 2019 Community Edition 16.6.3, Virtual Box 6.0.22. Machine is Intel Xeon E5-1650.
I could start the sample application without any issues. I attached the created binaries. Maybe you can try them and report back whether they run or not.
[Coin3DissueWin7.zip](https://github.com/coin3d/sowin/files/5017455/Coin3DissueWin7.zip)

**Comment by Deviaphan** [comment]
> I could start the sample application without any issues. I attached the created binaries. Maybe you can try them and report back whether they run or not.

Thank you for your attention! This example is worked! Even when I recompile Coind3d/SoWin and replace your dll's. But!
crash.exe, embedded.exe, multiview.exe, standalone.exe from sowin-build/bin still stuck.
This sample app used own message loop or SoWin::mainLoop? I have problems only with SoWin::mainLoop, but with own MFC message loop (messages from timer or mouse or keyboard - no matter) and manual call "Redraw" works perfect.

And one more thing. I have different DLL sizes. Builded with all default CMake settings

![00](https://user-images.githubusercontent.com/20601357/89247333-4eb12900-d637-11ea-8192-b782717416bb.png)

**Comment by Deviaphan** [comment]
All CMake projects. Compiling with Release-x64 then manual build INSTALL in order coin, sowin, simage. boost_1_73_0.

![01](https://user-images.githubusercontent.com/20601357/89247528-b9fafb00-d637-11ea-8189-1da0b02c7e99.png)
![02](https://user-images.githubusercontent.com/20601357/89247548-c7b08080-d637-11ea-9436-f2f475fdba9d.png)
![03](https://user-images.githubusercontent.com/20601357/89247532-bb2c2800-d637-11ea-9ca9-26c85820b7a4.png)
![04](https://user-images.githubusercontent.com/20601357/89247534-bbc4be80-d637-11ea-8cb3-d40b0863c126.png)
![05](https://user-images.githubusercontent.com/20601357/89247535-bbc4be80-d637-11ea-8316-9cc9820bc746.png)

**Comment by VolkerEnderlein** [comment]
That explains why it is running. The sample app used the MFC message loop, not the SoWin::mainLoop. Now I could reproduce the issue on the VM. I will investigate further.

**Comment by Deviaphan** [comment]
I'll clarify just in case, the problem is reproduced both on VM and on a **real PC** with Win7-x64.

**Comment by VolkerEnderlein** [comment]
I just merged pull request #34 that fixes this issue. WINVER and _WIN32_WINNT have to be set for newer Win SDKs to support previous windows versions. Thanks for the thorough issue report.

**Comment by Deviaphan** [comment]
Good news, thank you!
